# pull official base image
FROM ubuntu:20.04

# set work directory
WORKDIR /usr/src/cheverusapp

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHON_VERSION=3.8
ENV DEBIAN_FRONTEND=noninteractive

#
RUN apt update && \
    apt install build-essential -y && \
    apt install software-properties-common -y && \
    apt install libpq-dev -y && \
    apt install musl-dev -y && \
    apt install postgresql -y && \
    apt install gcc -y && \
    apt install curl -y && \
    apt install nano -y && \
    apt install telnet -y && \
    apt install pkg-config -y && \
    apt install libxmlsec1-dev -y && \
    apt install netcat -y && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt install python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-distutils -y && \
    rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python
RUN curl -s https://bootstrap.pypa.io/get-pip.py | python

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.dev.sh .

# copy project
COPY . .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/cheverusapp/entrypoint.dev.sh"]



