version: '3.7'

services:

  web:
    build:
      context: ./cheverusapp
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cheverusapp/:/usr/src/cheverusapp/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cheverus_admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cheverus_db

volumes:
  postgres_data: