# Generated by Django 3.0.7 on 2021-02-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='number_aimed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
